import type { Metadata } from "next";
import { Noto_Sans_Arabic } from "next/font/google";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import "./globals.css";
import Navbar from "./components/Navbar";

const notoSansArabic = Noto_Sans_Arabic({
  subsets: ["arabic"], // Crucial for Arabic characters
  display: "swap", // Recommended for performance
  weight: ["400", "700"], // Specify the weights you plan to use
  variable: "--font-noto-arabic", // Define a CSS variable name
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const direction = locale === "ar" || locale === "fa" ? "rtl" : "ltr";
  return (
    <html lang={locale} dir={direction}>
      <body className={`${notoSansArabic.variable} antialiased`}>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
